= JUXT Tech Test

This repository contains my submission for the JUXT technical test.

=== Screenshot of Weather Component

image::http

== Discussion

Initially I had planned to write this in a literate style, so that generating this brief, and additional documentation could be done
using lein-marginalia. In the interest of not having this be repo mostly comments, I decided to put that by the wayside and attempt to communicate intent through
docstrings and commit logs.

Trying to conceptualise what parts of state and data need to be passed around between sub-components and reacting to user input stood out to me as the exact use case for re-frame,
especially in the case of the drop-down menu/typeahead and refresh button. I had planned on doing that from the start, but felt that trying to make sure I was
using it correctly for the last part of the task would be counter-productive. Given more time, I would use re-frame to help with completing the third part of the task in a manner more representative of production-ready Clojure.
